DROP TABLE IF EXISTS properties;

CREATE TABLE properties (
	KEY VARCHAR(256) NOT NULL ,
	VALUE VARCHAR(1024) NULL ,
	APPLICATION VARCHAR(128) NOT NULL ,
	PROFILE VARCHAR(128) NOT NULL,
	LABEL VARCHAR(128) NOT NULL,
	PRIMARY KEY (KEY, APPLICATION, PROFILE, LABEL)
);
